services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mariadb/data
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: id
      MARIADB_PASSWORD: pw
      MARIADB_ROOT_PASSWORD: root
